### ISSUE TITLE
non-x86 compile failure

### ISSUE THREAD

**Issue by epi052** [rustysec/fuzzyhash-rs#9]
Good afternoon!  I recently started using your library in my project [feroxbuster](https://github.com/epi052/feroxbuster), thank you for creating it! 

@HenryHoggard filed a [bug report](https://github.com/epi052/feroxbuster/issues/180) on feroxbuster letting me know that compilation fails on arm.  He was awesome enough to provide a patch along with a great example fix in another project. I'm shamelessly stealing all the resources he provided to submit this issue and the associated PR.  

The issue boils down to the use of an i8 instead of a c_char in lib.rs.  Please see the PR for additional info/references.

**Comment by rustysec** [comment]
thank you so much for this! i will have a chance to review later tonight.

**Comment by rustysec** [comment]
Thanks for the report and PR. I went ahead and published to crates.

**Comment by epi052** [comment]
Awesome, thank you!
